spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      native:
#        search-locations: "classpath:/config"
         search-locations: "file:///F:/documents/files"
server:
  port: 8071